# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'joybox'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'asteroids'
  app.device_family = [:ipad]
  app.interface_orientations = [:landscape_left]
  app.icons = ['icon.png','icon@2x.png']
  app.prerendered_icon = true
end
